name: PyPI

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: "poetry"

      - name: Install apt dependencies
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libpq-dev wget build-essential zlib1g-dev libjpeg-dev python3-pythonmagick libmagic-dev inkscape xvfb poppler-utils libfile-mimeinfo-perl qpdf libimage-exiftool-perl ufraw-batch ffmpeg imagemagick libreoffice scribus
          version: 1.0

      - name: Install dependencies
        run: |
          python -m pip install -U twine
          poetry install

      - name: Build package
        run: poetry build

      - name: Upload to PyPI
        run: twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
          TWINE_NON_INTERACTIVE: true
